name: build forwarder test

on:
  push:
    branches: ['master']
    tags:
      - rev-*
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.19', '1.20', '1.21.x' ]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Setup git config
        run: git config --global url."ssh://git@github.com".insteadOf "https://github.com"

      - name: build
        run: |
          go build
          ls -l
          id

      - name: Setup ssh agent
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add /home/runner/.ssh/id_rsa
          ssh-add -l
        
      - name: build image
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: docker build . --platform linux/amd64 --ssh default -t test-build -f Dockerfile
